do NOT use mediump explicitly for GLSL130 because this seems incompatible with inout
0(97) : error C7538: OpenGL does not allow 'mediump' after 'inout'

git-svn-id: svn://svn.icculus.org/twilight/trunk/darkplaces@11079 d7cf8633-e32d-0410-b094-e92efae38249
::stable-branch::merge=f9923b69f7589cf0f373a62b8345a1c8b199859e